project:
  type: book
  output-dir: "RTP-summary-notebook"
  
book:
  title: "<br>Soundcast RTP Summary"
  repo-url: https://github.com/psrc/soundcast
  search: false
  sidebar:
    logo: ../notebook_styling/PSRClogo2016path.png

  chapters:
    - index.qmd
    - nb/RTP_topsheet.ipynb
    - nb/RTP_person.ipynb
    - nb/RTP_household.ipynb
    - nb/RTP_access.ipynb
    - nb/RTP_costs.ipynb
    - nb/RTP_walk_bike.ipynb
    - nb/RTP_emissions.ipynb
    - nb/RTP_MIC.ipynb
    - nb/RTP_mode_share.ipynb
    - nb/RTP_freight.ipynb
    - nb/RTP_congestion.ipynb
    - nb/RTP_transit.ipynb
    - nb/RTP_conformity_analysis.ipynb
        

format:
  html:
    mainfont: Poppins
    theme: 
      light: [cosmo, ../notebook_styling/custom.scss]
      dark: [darkly, ../notebook_styling/custom.scss]
    echo: false
    code-tools: true

toc: true
warning: false