name: model_py3
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=20.3.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blosc=1.21.0=h0e60522_0
  - brotlipy=0.7.0=py37hcc03f2d_1001
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2021.1.19=haa95532_1
  - certifi=2020.12.5=py37haa95532_0
  - cffi=1.14.5=py37hd8e9650_0
  - chardet=4.0.0=py37h03978a9_1
  - cryptography=3.4.7=py37h20c650d_0
  - et_xmlfile=1.0.1=py_1001
  - greenlet=1.0.0=py37hd77b12b_2
  - h5py=2.10.0=py37h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=3.7.3=py37haa95532_1
  - intel-openmp=2020.2=254
  - jdcal=1.4.1=py_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - lzo=2.10=he774522_1000
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37h196d8e1_0
  - mkl_fft=1.3.0=py37h46781fe_0
  - mkl_random=1.1.1=py37h47e9c7a_0
  - mock=4.0.3=py37h03978a9_1
  - numexpr=2.7.3=py37h08fd248_0
  - numpy=1.19.2=py37hadc3359_0
  - numpy-base=1.19.2=py37ha3acd2a_0
  - openpyxl=3.0.7=pyhd3eb1b0_0
  - openssl=1.1.1k=h2bbff1b_0
  - pandana=0.6.1=py37h90003fb_0
  - pandas=1.2.3=py37hf11a4ad_0
  - pip=21.0.1=py37haa95532_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyreadline=2.1=py37_1
  - pysocks=1.7.1=py37h03978a9_3
  - pytables=3.6.1=py37h1da0976_0
  - python=3.7.10=h6244533_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.7=1_cp37m
  - pytz=2021.1=pyhd3eb1b0_0
  - requests=2.25.1=pyhd3deb0d_0
  - scikit-learn=0.24.1=py37hf11a4ad_0
  - scipy=1.6.2=py37h14eb087_0
  - service_identity=18.1.0=py37h28b3542_0
  - setuptools=52.0.0=py37haa95532_0
  - six=1.15.0=py37haa95532_0
  - sqlalchemy=1.4.5=py37h2bbff1b_0
  - sqlite=3.35.4=h2bbff1b_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - urllib3=1.26.4=pyhd8ed1ab_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.2=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py37h03978a9_2
  - wincertstore=0.2=py37_0
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xlsxwriter=1.3.8=pyhd3eb1b0_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
prefix: C:\Users\Modeller\Anaconda3\envs\model_py3
