################################################################
# Validation input files and output directory names
################################################################

model_dir = "//modelstation4/c$/workspace/sc_2023/soundcast"
survey_dir = "R:/e2projects_two/2023_base_year/2023_survey/daysim_format/cleaned/skims_attached/uncloned"
tour_survey_dir = "R:/e2projects_two/2023_base_year/2023_survey/daysim_format/cleaned/skims_attached"
base_year = "2018"

# other validation dataset
p_acs_auto_ownership = "R:/e2projects_two/activitysim/estimation/2017_2019_data/validation_data/auto_ownership/bg_auto_ownership.csv"
p_maz_bg_lookup =      "R:/e2projects_two/activitysim/estimation/2017_2019_data/validation_data/auto_ownership/maz_bg_lookup.csv"

# validation output directory
p_output_dir = "outputs/validation"

################################################################
# run validation notebooks
################################################################
summary_list = ['validation_scripts/telecommute',
               'validation_scripts/work_location',
               'validation_scripts/transit_pass_ownership',
               'validation_scripts/school_location',
               'validation_scripts/auto_ownership',
               'validation_scripts/work_tour_mode',
               'validation_scripts/school_tour_mode',
               'validation_scripts/escort_tour_mode',
               'validation_scripts/other_home_based_tour_mode']
#summary_list = ['validation_scripts/work_location']

# color palatte for plots
psrc_color = ["#91268F", "#8CC63E", "#00A7A0", "#F05A28", "#4C4C4C", "#630460", "#9f3913", "#588527", "#00716c", "#3e4040"]