project:
  type: book
  output-dir: "../telecommute-analysis-notebook"
  
book:
  title: "Telecommute Analysis"
  repo-url: https://github.com/psrc/soundcast/tree/base_year_2023/scripts/summarize/validation
  search: false
  sidebar:
    logo: ../../notebook_styling/PSRClogo2016path.png

  chapters:
    - index.qmd
    - telecommute_analysis.ipynb

format:
  html:
    mainfont: Poppins
    theme: 
      light: [cosmo, ../../notebook_styling/custom.scss]
      dark: [darkly, ../../notebook_styling/custom.scss]
    echo: false
    code-tools: true

toc: true
warning: false




