project:
  type: book
  output-dir: "network-validation-notebook"
  
book:
  title: "Network Validation"
  repo-url: https://github.com/psrc/soundcast/tree/base_year_2023/scripts/summarize
  search: false
  sidebar:
    logo: ../notebook_styling/PSRClogo2016path.png

  chapters:
    - index.qmd
    - nb/traffic_validation.ipynb
    - nb/transit_validation.ipynb
    - nb/bike_validation.ipynb
    - nb/link_analysis.ipynb
    - nb/JBLM.ipynb
    - nb/supplementals.ipynb

format:
  html:
    mainfont: Poppins
    theme: 
      light: [cosmo, ../notebook_styling/custom.scss]
      dark: [darkly, ../notebook_styling/custom.scss]
    echo: false
    code-tools: true
    warning: false

toc: true




